# schema: "**/*.graphqls"
# documents: "**/*.graphql"
# plugins:
#   - typescript
# schema: http://localhost:4000/graphql
schema: ${NEXT_PUBLIC_GRAPHQL_API_ENDPOINT}
documents: ./src/framework/graphql/**/*.graphql
plugins:
  - typescript-operations
  - typescript-react-apollo
cacheDir: __generated__
